### ISSUE TITLE
groovyx.net.http.HttpResponseException: Bad Request

### ISSUE THREAD

**Issue by mmoayyed** [stempler/gradle-versioneye-plugin#11]
```
:versioneye-update
Executing task ':versioneye-update' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:versioneye-update FAILED
:versioneye-update (Thread[Daemon worker Thread 4,5,main]) completed. Took 3.502 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':versioneye-update'.
> groovyx.net.http.HttpResponseException: Bad Request
```

Gradle 2.9.

**Comment by reiz** [comment]
@mmoayyed @stempler Not sure. But maybe it's related to this here: http://blog.versioneye.com/2015/12/11/api-breaking-change-project_key-project_id/

**Comment by stempler** [comment]
Fixed and included in `1.1.0` release. Also, the project key is no longer stored in the properties when using `versioneye-create`.

@reiz Maybe you want to update your API documentation as well - it is kind of misleading that the parameters are still named `project_key`, even if the parameter description says *Project ID*. After all, the `project_key` is still there, as it is returned in the response when creating a project.

**Comment by johnjohndoe** [comment]
@stempler As mentioned in #10: I updated to version 1.1.0 and run `./gradlew vEU`. This fails with the following error:

> java.lang.UnsupportedClassVersionError: org/standardout/gradle/plugin/versioneye/VersionEyePlugin : Unsupported major.minor version 52.0

The following stacktrace is printed before the mentioned error:

```
Parallel execution is an incubating feature.
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:599)
	at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:566)
	at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:563)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
	at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:562)
	at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:559)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:499)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stempler** [comment]
@johnjohndoe 

This time built with Java 8 - I will try to add source and target compatibility settings for it to work with older Java versions (new issue #12). Did not think about that - the settings were not in place as it was no issue before.

About the stacktrace - seems to be related to some kind of Anrdoid plugin that complains about a missing `buildToolsVersion`. I have no idea how that can be related to the versioneye plugin or how to fix this. If you think it is an issue with the plugin and have a pointer to what is the problem, please create a new issue.

**Comment by johnjohndoe** [comment]
Does this mean I can use the plugin only with Java 8?

I did not touch my projects over the last weeks - I simply increased the version of the plugin to get it running again since version 1.0.1 failed with `groovyx.net.http.HttpResponseException: Bad Request` as I reported.

**Comment by mmoayyed** [comment]
Tried again with 1.2. This is certainly not fixed. Same error, and I am on Java 8.

**Comment by reiz** [comment]
@mmoayyed Sorry for that. We plan to refactor this plugin until end of March and fix all the issues.

**Comment by mmoayyed** [comment]
No worries. Thanks for your help.

I do with versioneye had native support for Gradle. It seems like they do to some degree, yet they are not able to parse properties correctly. Just FYI, this is the project I am working on: https://github.com/Jasig/cas

**Comment by reiz** [comment]
@mmoayyed Cool Project you are working on! 

Currently we don't have native support on the server side. The native support for Gradle is implemented in the VersionEye Gradle Plugin. @stempler is working on it and until end of this month it should have the same features as the [VersionEye Maven Plugin](https://github.com/versioneye/versioneye_maven_plugin) ;-)

**Comment by stempler** [comment]
@mmoayyed The breaking change in the VersionEye API that caused the update task for fail for everyone was fixed in 6acbd51. Your problem seems to be something else, maybe a configuration problem, at least I can't reproduce it other than using an invalid project ID.

I improved the error reporting for failed requests in the current snapshot (`1.3.0-SNAPSHOT`). You should try it and see if you get more information there. You should get a message like this:
```
Unexpected failure accessing VersionEye API: HTTP/1.1 400 Bad Request (Project `xyz` don't exists)
```

Use the Snapshot version in your build with a configuration similar to this:

```groovy
buildscript {
  repositories {
    maven {
      url 'http://oss.sonatype.org/content/repositories/snapshots/'
    }
  }
  dependencies {
    classpath 'org.standardout:gradle-versioneye-plugin:1.3.0-SNAPSHOT'
  }
}

apply plugin: 'org.standardout.versioneye'
```

**Comment by mmoayyed** [comment]
Thanks. On the TODO list.

**Comment by mmoayyed** [comment]
1.3 seems to have solved the problem. Running the plugin on https://github.com/Jasig/cas is going through successfully. Thanks!

**Comment by stempler** [comment]
Good to hear. Thanks for the feedback!
